CREATE TABLE Perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    nome NVARCHAR(50) NOT NULL,
    sobrenome NVARCHAR(50),
    telefone VARCHAR(20),
    senha VARBINARY(32) NOT NULL,
    cod_status BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT UQ_Perfil_Email UNIQUE (email)
);

CREATE VIEW PerfilAtivo AS
SELECT id, email, nome, sobrenome, telefone
FROM Perfil
WHERE cod_status = TRUE;

CREATE TABLE Plano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome NVARCHAR(50) NOT NULL,
    wallpaper_url VARCHAR(2048),
    perfil_id BIGINT NOT NULL,
    CONSTRAINT FK_Plano_Perfil FOREIGN KEY (perfil_id)
        REFERENCES Perfil(id)
        ON DELETE CASCADE
);

CREATE TABLE Lista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome NVARCHAR(50) NOT NULL,
    cor CHAR(7),
    plano_id BIGINT NOT NULL,
    CONSTRAINT FK_Lista_Plano FOREIGN KEY (plano_id)
        REFERENCES Plano(id)
        ON DELETE CASCADE
);

CREATE TABLE Cartao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome NVARCHAR(50) NOT NULL,
    descricao NVARCHAR(500),
    cor CHAR(7),
    lista_id BIGINT NOT NULL,
    CONSTRAINT FK_Cartao_Lista FOREIGN KEY (lista_id)
        REFERENCES Lista(id)
        ON DELETE CASCADE
);

CREATE TABLE Tarefa (
    id BIGINT PRIMARY KEY,
    data_conclusao DATETIME2(0) NOT NULL,
    CONSTRAINT FK_Tarefa_Cartao FOREIGN KEY (id)
        REFERENCES Cartao(id)
        ON DELETE CASCADE
);

CREATE TABLE Evento (
    id BIGINT PRIMARY KEY,
    data_inicio DATETIME2(0) NOT NULL,
    data_fim DATETIME2(0) NOT NULL,
    CONSTRAINT FK_Evento_Cartao FOREIGN KEY (id)
        REFERENCES Cartao(id)
        ON DELETE CASCADE,
    CONSTRAINT CK_Evento_Data CHECK (data_fim >= data_inicio)
);

CREATE INDEX IX_Plano_Perfil ON Plano(perfil_id);
CREATE INDEX IX_Lista_Plano ON Lista(plano_id);
CREATE INDEX IX_Cartao_Lista ON Cartao(lista_id);
